version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: coffee-chat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: coffee-chat
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build: ./backend
    container_name: coffee-chat-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/coffee-chat?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRE=7d
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb_data: 